blank_issues_enabled: true
contact_links:
  - name: Security issue
    url: https://github.com/Alexander-Hung/NaviProxy/security/advisories/new
    about: Please report sensitive security issues privately.
